name: live_event
description: An event without data, using StreamController to be used in flutter projects.
version: 1.0.0
homepage: https://github.com/javaherisaber/live_event

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
